language: python

matrix:
  include:
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.4.1

env:
  - APP_CONFIG_NAME=test

script:
  - flake8 middleware/ --ignore=F401,F403,F405
  - pytest
  - coverage run tests.py

install:
 - pip install -r requirements.txt
 - pip install codecov

after_success:
  - codecov

before_script:
 - "export PYTHONPATH=."
