language: python

matrix:
  include:
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.4.1

env:
  - APP_CONFIG_NAME=test

script:
  - pytest
  - flake8 middleware/ --ignore=F401,F403,F405
install:
 - pip install -r requirements.txt

before_script:
 - "export PYTHONPATH=."
