language: python

matrix:
  include:
    - python: 3.6
script:
  - pytest
  - flake8 .
branches:
  only:
    - stuart-wip
install:
 - pip install -r requirements.txt

before_script:
 - "export PYTHONPATH=."
