language: python

matrix:
  include:
    - python: 3.6
script:  # Handles creating a blank config file so imports dont fail
  - mkdir -p instance
  - cd instance
  - touch config.py
  - cd ..
  - pytest
  - flake8 middleware/ --ignore=F403,F405
install:
 - pip install -r requirements.txt

before_script:
 - "export PYTHONPATH=."
