language: python

matrix:
  include:
    python:
      - "3.2"
      - "3.3"
      - "3.4"
      - "3.4.1"
      - "3.5"
      - "3.6"

script:  # Handles creating a blank config file so imports dont fail
  - mkdir -p instance
  - touch instance/config.py
  - pytest
  - flake8 middleware/ --ignore=F403,F405
install:
 - pip install -r requirements.txt

before_script:
 - "export PYTHONPATH=."
