environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"

install:
  # We need wheel installed to build wheels
  #- "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"

build: off

test_script:
  - ps: mkdir -p instance
  - ps: touch instance/config.py
  - "%PYTHON%\\python.exe -m pytest"
